apiVersion: v1
kind: Service
metadata:
  name: talana-postgres
  labels:
    app: talana
spec:
  ports:
    - port: 5432
  selector:
    app: talana
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: talana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana-postgres
  labels:
    app: talana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talana
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: talana
        tier: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.name }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.pass }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim