apiVersion: v1
kind: Service
metadata:
  name: talana-rabbitmq
  labels:
    app: talana
spec:
  ports:
    - port: 5672
  selector:
    app: talana
    tier: rabbitmq
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-claim
  labels:
    app: talana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana-rabbitmq
  labels:
    app: talana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talana
      tier: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: talana
        tier: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.pass }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.rabbitmq.vhost }}
        ports:
        - containerPort: 5672
          name: rabbitmq
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim