apiVersion: v1
kind: Service
metadata:
  name: talana
  labels:
    app: talana
spec:
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: talana
    tier: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana
  labels:
    app: talana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talana
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: talana
        tier: api
    spec:
      containers:
      - image: devops-test_api
        name: talana
        imagePullPolicy: Never
        command: "uvicorn main:app --reload --host 0.0.0.0 --port 80"
        env:
        - name: MQ_HOST
          value: {{ .Values.rabbitmq.host }}
        - name: MQ_PORT
          value: {{ .Values.rabbitmq.port }}
        - name: MQ_USER
          value: {{ .Values.rabbitmq.user }}
        - name: MQ_PASS
          value: {{ .Values.rabbitmq.pass }}
        - name: MQ_VHOST
          value: {{ .Values.rabbitmq.vhost }}
        ports:
        - containerPort: 80
          name: talana